export const
  MASTER = 'master',
  AGENT = 'agent',
  WORKER = 'worker',
  BROKER = 'broker',
  LIAISON = 'liaison',
  APP = 'app',
  PARENT = 'parent',
  SERVER = 'server',
  VENDOR = 'vendor',
  CLIENT = 'client',
  CHEF = 'chef',
  TOURNANT = 'tournant',
  ABOYEUR = 'aboyeur',
  MESSENGER = 'messenger'